default_settings: null
behaviors:
  My Behavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 4096
      learning_rate: 1e-4
      beta: 0.005
      epsilon: 0.23
      lambd: 0.94
      num_epoch: 4
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: resnet
      use_recurrent: true
      memory:
        sequence_length: 32
        memory_size: 512
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      curiosity:
        strength: 0.01
        gamma: 0.99
        network_settings:
          hidden_units: 64
          num_layers: 3
        learning_rate: 1e-4
    init_path: null
    keep_checkpoints: 2
    checkpoint_interval: 500000
    max_steps: 5e5
    time_horizon: 2560
    summary_freq: 1000
    threaded: false
    self_play: null
    behavioral_cloning:
      demo_path: Assets/Demonstrations/final/1.demo
      strength: 0.5
      steps: 500000
      samples_per_update: 10240
      num_epoch: 4
      batch_size: 32
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  num_areas: 1
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
engine_settings:
  width: 156
  height: 156
  quality_level: 4
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters: null
torch_settings:
  device: cuda
debug: false
