default_settings: null
behaviors:
  My Behavior:
    trainer_type: sac
    hyperparameters:
      batch_size: 32
      buffer_size: 40960
      buffer_init_steps: 4096
      init_entcoef: 0.1
      learning_rate: 1e-4
      tau: 0.005
      learning_rate_schedule: constant
      train_interval: 4
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: resnet
      use_recurrent: true
      memory:
        sequence_length: 32
        memory_size: 512
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 64
          num_layers: 2
        learning_rate: 1e-4
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 100000
    max_steps: 500000
    time_horizon: 256
    summary_freq: 1000
    threaded: false
    self_play: null
    behavioral_cloning: null
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  num_areas: 1
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
engine_settings:
  width: 156
  height: 156
  quality_level: 4
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters: null
torch_settings:
  device: cuda
debug: false
