default_settings: null
behaviors:
  My Behavior:
    trainer_type: sac
    hyperparameters:
      batch_size: 32
      buffer_size: 10240
      learning_rate: 1e-4
      learning_rate_schedule: constant
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 1
      save_replay_buffer: false
      init_entcoef: 0.5
      reward_signal_steps_per_update: 1
    network_settings:
      normalize: false
      hidden_units: 64
      num_layers: 3
      vis_encode_type: resnet
      use_recurrent: true
      memory:
        sequence_length: 32
        memory_size: 512
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 64
          num_layers: 3
        learning_rate: 1e-4
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 100000
    max_steps: 500000
    time_horizon: 128
    summary_freq: 1000
    threaded: false
    self_play: null
    behavioral_cloning:
      demo_path: Assets/Demonstrations/third1ghost.demo
      strength: 0.5
      steps: 500000
      samples_per_update: 2048
      num_epoch: 4
      batch_size: 32
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  num_areas: 1
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
engine_settings:
  width: 156
  height: 156
  quality_level: 4
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters: null
torch_settings:
  device: cuda
debug: false
